// Topic decks, business group: the plan for each is a look, deck meta and a
// slide sequence with its own copy. See scripts/gen-topic-decks.mjs.

export default [
  {
    id: "deck-sales-qbr", title: "Sales QBR", look: "atlas", rank: 32,
    tags: ["qbr", "sales", "review", "quarterly"],
    meta: { company: "Northwind Systems", deck: "Sales QBR, Q3 2026", kicker: "Quarter in review", farewell: "On to Q4",
      art: { cover: "la-success-illustration", section: "il-day5-vault", picture: "la-conversation-illustration", closing: "la-scooter" } },
    slides: [
      ["cover", { title: "Pipeline, wins,\nand what changed", subtitle: "Bookings against plan, the plays that closed, and the three bets that carry us into Q4.", presenter: "Marcus Obi, VP Sales  ·  8 October 2026" }],
      ["agenda", { title: "Sixty minutes, five questions", items: [
        ["Headline numbers", "Bookings, coverage and win rate against plan", "10 min"],
        ["What worked", "The plays and segments that outperformed", "10 min"],
        ["What did not", "Stalled deals and the losses we should have won", "15 min"],
        ["Competitive picture", "Who we met and how we positioned", "10 min"],
        ["The Q4 plan", "Three bets, owners and dates", "15 min"],
      ], card: { eyebrow: "This session", big: "Q3", meta: [["When", "8 October, 14:00"], ["Room", "Summit, level 6"], ["Host", "Marcus Obi"], ["Deck", "Shared after the call"]] } }],
      ["figures", { eyebrow: "Headline numbers", title: "The quarter against plan", stats: [
        ["$12.4M", "Bookings", "103% of plan", "Closed-won ACV; enterprise carried the last two weeks."],
        ["3.4x", "Pipeline coverage", "+0.6x entering Q4", "Qualified pipeline against the Q4 number, before marketing's October push."],
        ["31%", "Win rate", "+4 pts", "Up in mid-market, flat in enterprise; the security review is the swing factor."],
        ["41 days", "Sales cycle", "−9 days", "Faster where the pilot offer was used; slower everywhere else."],
      ] }],
      ["chart", { eyebrow: "Headline numbers", title: "Bookings by month", takeaway: "September closed 44% of the quarter; the pilot offer pulled two enterprise deals forward.", categories: ["Jul", "Aug", "Sep"], series: [{ name: "Plan", values: [3.6, 4.0, 4.4] }, { name: "Actual", values: [3.1, 3.8, 5.5] }], calls: [["$5.5M", "September bookings, a record month"], ["7", "Deals over $250K, four with the pilot offer"], ["2", "Deals slipped into October"]] }],
      ["twoColumns", { eyebrow: "What worked, what did not", title: "The honest split", left: { eyebrow: "Worked", head: "The pilot offer and the mid-market play", lines: ["Two-week pilots closed at 2x the rate", "Mid-market reps hit 118% of quota", "Partner-sourced deals churned least"], icon: "circle-check" }, right: { eyebrow: "Did not", head: "Enterprise security reviews", lines: ["Six deals stalled at the review stage", "Three losses to the incumbent on price", "Discounting crept back above policy"], icon: "alert-triangle" } }],
      ["table", { eyebrow: "Competitive picture", title: "Who we met, and how it went", cols: ["", "Us", "Incumbent", "Upstart"], rows: [["Met in deals this quarter", "", "38", "17"], ["Won when we led with pilots", "yes", "no", "no"], ["Security certification", "yes", "yes", "no"], ["Sub-30-day implementation", "yes", "no", "yes"], ["Price under $40 per seat", "no", "no", "yes"]] }],
      ["threeCards", { eyebrow: "The Q4 plan", title: "Three bets, with owners", cards: [["flag", "Pilots for every enterprise deal", "Make the two-week pilot the default. Owner: Priya. Target: 60% of enterprise pipeline."], ["shield", "Security review in under ten days", "A pre-answered questionnaire and a named engineer. Owner: Sam. Target: no deal stalls past day ten."], ["coin", "Hold the line on discounting", "Approval above 15% moves to the VP. Owner: Marcus. Target: average discount under 12%."]] }],
      ["closing", { title: "Questions", subtitle: "The full pipeline review and the rep-by-rep numbers are in the shared folder.", rows: [["mail", "marcus@northwind.example"], ["world", "northwind.example/sales"], ["calendar", "Next QBR: 14 January"]], cta: "Book a follow-up" }],
    ],
  },
  {
    id: "deck-annual-report", title: "Annual Report", look: "atlas", rank: 64,
    tags: ["annual", "report", "year", "review"],
    meta: { company: "Harbor & Vale", deck: "Annual report 2026", kicker: "Twelve months, one story", farewell: "With thanks",
      art: { cover: "la-building", section: "il-day54-building", picture: "la-conversation-illustration", closing: "la-success-illustration" } },
    slides: [
      ["cover", { title: "The year we\ngrew up", subtitle: "Growth, customers and the team, and the moments that tested us along the way.", presenter: "Elena Sato, Chief Executive  ·  February 2027" }],
      ["figures", { eyebrow: "By the numbers", title: "The year in four figures", stats: [["$64M", "Revenue", "+28% year over year", "Second consecutive year above plan, with services now a fifth of the mix."], ["2,900", "Customers", "+610 net new", "Three of the ten largest arrived through partners."], ["186", "People", "+52 this year", "Two new offices, one of them our first outside the country."], ["94%", "Customer retention", "+3 pts", "Highest on record; the support rebuild paid for itself by August."]] }],
      ["section", { n: "01", title: "The big moments", blurb: "Four quarters, four things that changed the company." }],
      ["timeline", { eyebrow: "The big moments", title: "Quarter by quarter", done: 4, steps: [["Q1", "The platform relaunch", "Six months of rebuild shipped in one week, with no customer downtime."], ["Q2", "The Lisbon office", "Our first team outside the country, twenty-two people by year end."], ["Q3", "The partner programme", "Forty partners signed; a third of new customers now arrive through them."], ["Q4", "The thousandth enterprise seat", "Signed in December, on a call that started as a support ticket."]] }],
      ["twoColumns", { eyebrow: "The hard parts", title: "What tested us", left: { eyebrow: "What went wrong", head: "The outage in May", lines: ["Nine hours, four hundred customers affected", "Root cause in a vendor we had not audited", "Two customers left over it"], icon: "alert-triangle" }, right: { eyebrow: "What we changed", head: "Reliability became a team", lines: ["Every vendor audited by September", "A named on-call owner for each service", "Uptime above 99.95% since June"], icon: "circle-check" } }],
      ["quote", { text: "They told us what broke, what they were doing about it, and when it would be fixed. That is why we stayed.", name: "Rowan Achebe", role: "Chief Information Officer, Brightline Logistics" }],
      ["team", { eyebrow: "Thank you", title: "The people who made it", people: [["Elena Sato", "Chief Executive", "Set the plan and kept every promise in it."], ["Marcus Obi", "Chief Operating Officer", "Opened Lisbon and built the partner programme."], ["Priya Raman", "Head of Product", "Led the relaunch and the platform team."], ["Dana Whitfield", "Head of Customers", "Rebuilt support and won back the trust."]] }],
      ["closing", { title: "The year ahead", subtitle: "Three markets, one new product line, and the same promise: tell the truth early.", rows: [["mail", "elena@harborvale.example"], ["world", "harborvale.example/2026"], ["file-text", "Full report and accounts attached"]], cta: "Read the full report" }],
    ],
  },
  {
    id: "deck-investor-update", title: "Investor Update", look: "slate", rank: 54,
    tags: ["investors", "update", "metrics", "startup"],
    meta: { company: "Beacon", deck: "Investor update, September", kicker: "monthly update, no spin", farewell: "Thank you for reading",
      art: { cover: "la-working-1", section: "il-day37-calculator", picture: "la-woman-working-1", closing: "la-scooter" } },
    slides: [
      ["cover", { title: "September\nin one page", subtitle: "Revenue, burn and runway, what went right, what went wrong, and the three things we need from you.", presenter: "Sam Whitfield, Chief Executive  ·  4 October 2026" }],
      ["figures", { eyebrow: "Metrics", title: "The four numbers", stats: [["$412K", "Monthly recurring revenue", "+9% month over month", "Fourth straight month above 8%; expansion was a third of it."], ["$310K", "Net burn", "Flat", "Two hires offset by the office move; contractors down to one."], ["21", "Months of runway", "Plan holds", "At current burn, before any of the pipeline closes."], ["112%", "Net revenue retention", "+2 pts", "Churn fell to 1.1%; two accounts doubled seats."]] }],
      ["chart", { eyebrow: "Metrics", title: "Revenue and burn, six months", takeaway: "Revenue has grown every month since April; burn has not moved. The gap is closing on schedule.", categories: ["Apr", "May", "Jun", "Jul", "Aug", "Sep"], series: [{ name: "MRR", values: [268, 292, 318, 346, 378, 412] }, { name: "Net burn", values: [305, 312, 298, 315, 308, 310] }], calls: [["$412K", "MRR at month end"], ["1.1%", "Logo churn, the lowest yet"], ["Q2 2027", "Default-alive at this trajectory"]] }],
      ["twoColumns", { eyebrow: "Highlights and lowlights", title: "What went right, what went wrong", left: { eyebrow: "Right", head: "The self-serve tier started paying", lines: ["Thirty-one upgrades without a sales call", "Payback under four months on that cohort", "Support tickets per account down 40%"], icon: "circle-check" }, right: { eyebrow: "Wrong", head: "We lost the platform lead we wanted", lines: ["Counter-offer we could not match", "Search restarted with a new firm", "Roadmap slips by three weeks"], icon: "alert-triangle" } }],
      ["threeCards", { eyebrow: "Asks", title: "Three things we need", cards: [["user", "One introduction", "A head of platform engineering, ideally someone who has scaled a data pipeline past a billion events a day."], ["briefcase", "Two customer intros", "Logistics or fleet operators with more than 500 vehicles. Two names would change Q4."], ["message", "Thirty minutes of advice", "Pricing for the self-serve tier. We think we are underpriced by half and want a second opinion."]] }],
      ["closing", { title: "Thank you", subtitle: "Reply to this deck with anything; we read every note. The data room is updated with the September actuals.", rows: [["mail", "sam@beacon.example"], ["world", "beacon.example/investors"], ["calendar", "Next update: 4 November"]], cta: "Open the data room" }],
    ],
  },
  {
    id: "deck-budget-review", title: "Budget Review", look: "atlas", rank: 88,
    tags: ["budget", "finance", "review", "planning"],
    meta: { company: "Cobalt Health", deck: "Budget review, H1 2026", kicker: "Spend against plan", farewell: "Decision today",
      art: { cover: "la-woman-working-2", section: "il-day37-calculator", picture: "la-desk-illustration-2", closing: "la-working-2" } },
    slides: [
      ["cover", { title: "Where the\nmoney went", subtitle: "Actuals against plan for the first half, the variances that matter, and one reallocation to approve.", presenter: "Dana Whitfield, Finance Director  ·  15 July 2026" }],
      ["figures", { eyebrow: "The picture", title: "First half against plan", stats: [["$18.6M", "Total spend", "97% of plan", "Under plan in headcount, over in cloud and travel."], ["$1.2M", "Headcount underspend", "14 roles open", "Hiring ran two months behind; the gap closes by October."], ["$640K", "Cloud overspend", "+22% vs plan", "Usage grew faster than forecast; reserved capacity was bought late."], ["$310K", "Travel overspend", "+31% vs plan", "Two conferences and the Lisbon office opening."]] }],
      ["chart", { eyebrow: "Where the money went", title: "Actuals by department", takeaway: "Engineering and sales are under plan on people; platform is over on infrastructure.", categories: ["Eng", "Sales", "Platform", "Marketing", "G&A"], series: [{ name: "Plan", values: [6.2, 4.8, 3.1, 2.9, 2.2] }, { name: "Actual", values: [5.6, 4.4, 3.7, 3.0, 1.9] }], calls: [["−$1.0M", "Under plan across engineering and sales"], ["+$600K", "Over plan in platform, all cloud"], ["$18.6M", "Total, 97% of plan"]] }],
      ["table", { eyebrow: "Variances", title: "The overs, the unders, and the why", cols: ["", "Plan", "Actual", "Variance"], rows: [["Engineering headcount", "$6.2M", "$5.6M", "−$0.6M"], ["Sales headcount", "$4.8M", "$4.4M", "−$0.4M"], ["Cloud and infrastructure", "$2.9M", "$3.5M", "+$0.6M"], ["Travel and events", "$1.0M", "$1.3M", "+$0.3M"], ["Software and tooling", "$0.9M", "$0.8M", "−$0.1M"]] }],
      ["threeCards", { eyebrow: "Reallocation proposal", title: "What we move, and what it buys", cards: [["database", "Reserve cloud capacity now", "Move $400K of the headcount underspend to reserved instances. Saves $180K in H2 against on-demand pricing."], ["user", "Fund two of the open roles as contractors", "Bridge the platform gap for six months while the hires land. $260K, fully within the underspend."], ["plane", "Cap travel for H2", "Conference attendance by approval only. Brings the line back to plan by December."]] }],
      ["closing", { title: "The decision", subtitle: "Approve the reallocation as proposed, adjust the amounts, or defer to the September review.", rows: [["mail", "dana@cobalthealth.example"], ["file-text", "Full variance workbook attached"], ["calendar", "Next review: 16 September"]], cta: "Approve the proposal" }],
    ],
  },
  {
    id: "deck-okr-review", title: "OKR Review", look: "vanta", rank: 52,
    tags: ["okr", "goals", "review", "metrics"],
    meta: { company: "Nova Systems", deck: "OKR review, Q3 2026", kicker: "// scored, honestly", farewell: "// next quarter",
      art: { cover: "la-ai-robot-3", section: "il-111-coding", picture: "la-woman-working-2", closing: "la-free-svg-illustrations-robots" } },
    slides: [
      ["cover", { title: "Three objectives,\nscored", subtitle: "What we set out to do in Q3, how far we got, and which targets were wrong versus which execution was.", presenter: "Priya Raman, Head of Product  ·  2 October 2026", chips: [["0.7", "avg score"], ["9", "key results"], ["2", "missed"]] }],
      ["figures", { eyebrow: "Objective one", title: "Make the platform boring to run", stats: [["99.97%", "Uptime", "Target 99.95%", "Scored 1.0. Two incidents, both under fifteen minutes."], ["−41%", "P95 latency", "Target −30%", "Scored 1.0. The cache layer landed in August."], ["14", "Pages on call per week", "Target 10", "Scored 0.6. Alert noise from the new region."], ["0.87", "Objective score", "Strong", "Reliability is no longer the conversation in customer calls."]] }],
      ["figures", { eyebrow: "Objective two", title: "Win the self-serve upgrade", stats: [["4.8%", "Free to paid conversion", "Target 6%", "Scored 0.5. Improved from 3.1%; the checkout redesign shipped late."], ["$92K", "Self-serve MRR", "Target $120K", "Scored 0.6. Growing 11% a month since the redesign."], ["31", "Upgrades per week", "Target 40", "Scored 0.7. Weekend upgrades appeared for the first time."], ["0.6", "Objective score", "Behind", "Right target, late execution. Carries into Q4 unchanged."]] }],
      ["figures", { eyebrow: "Objective three", title: "Ship the enterprise bundle", stats: [["Yes", "SSO and SCIM shipped", "On time", "Scored 1.0. Four customers live in the first week."], ["3", "Enterprise pilots", "Target 5", "Scored 0.5. Two pilots slipped on the customer side."], ["EU", "Data residency", "Target EU and APAC", "Scored 0.5. APAC region deferred to Q1."], ["0.67", "Objective score", "Mixed", "Product shipped; the pipeline did not follow as fast as planned."]] }],
      ["twoColumns", { eyebrow: "Lessons", title: "Wrong targets, or wrong execution?", left: { eyebrow: "Targets we set wrong", head: "Conversion at 6% assumed the redesign in July", lines: ["It shipped in September", "The number was right, the date was not", "Q4 keeps the target, moves the date"], icon: "alert-triangle" }, right: { eyebrow: "Execution we got wrong", head: "APAC residency waited on one person", lines: ["No backup owner for the region work", "Two weeks lost to a vacation", "Every key result now has a second owner"], icon: "circle-check" } }],
      ["threeCards", { eyebrow: "Next quarter", title: "Draft objectives for debate", cards: [["gauge", "Cut on-call pages in half", "Alert tuning first, then the noisy region. Owner: platform."], ["sparkles", "Self-serve at 6% conversion", "Same target, the redesign is now live. Owner: growth."], ["world", "APAC residency live by December", "Two owners, one date, weekly check. Owner: enterprise."]] }],
      ["closing", { title: "Questions", subtitle: "Scores and the evidence behind each are in the tracker. Push back on the drafts before Friday.", rows: [["mail", "priya@novasystems.example"], ["world", "okr.novasystems.example"], ["calendar", "Q4 objectives lock: 10 October"]], cta: "Open the tracker" }],
    ],
  },
  {
    id: "deck-all-hands", title: "Company All-Hands", look: "pulse", rank: 38,
    tags: ["all hands", "company", "update", "culture"],
    meta: { company: "Loop", deck: "All-hands, October", kicker: "October all-hands", farewell: "See you next month",
      art: { cover: "la-hero-image-2", section: "il-day35-firework", picture: "la-conversation-illustration", closing: "la-scooter" } },
    slides: [
      ["cover", { title: "What October\nlooked like", subtitle: "Wins worth naming, the numbers against plan, what we are fixing, and the people who made the month.", presenter: "Elena Sato, Chief Executive  ·  31 October 2026", year: "Oct" }],
      ["threeCards", { eyebrow: "Wins to celebrate", title: "Three wins worth naming", cards: [["trophy", "Brightline went live", "Our largest customer, 4,000 seats, migrated in a weekend. Not one ticket on Monday."], ["sparkles", "Self-serve crossed $100K", "Monthly revenue with no sales call, for the first time. Growth is now a real team."], ["heart", "Support hit a 96 satisfaction score", "Highest ever, with the queue at its longest. Thank the night shift."]] }],
      ["figures", { eyebrow: "The numbers", title: "Where we stand against plan", stats: [["$3.9M", "October revenue", "104% of plan", "Expansion carried it; new business was flat."], ["1,940", "Customers", "+86 this month", "Churn at 1.3%, back under target."], ["118", "People", "+7 this month", "Three in engineering, two in support, two in sales."], ["19", "Months of runway", "Plan holds", "Before the round, at the current burn."]] }],
      ["twoColumns", { eyebrow: "What we are fixing", title: "The honest view", left: { eyebrow: "Not working", head: "Onboarding takes too long", lines: ["Median time to first value: 11 days", "Half of new accounts need a call", "The import tool fails on large files"], icon: "alert-triangle" }, right: { eyebrow: "What we are doing", head: "A two-week onboarding sprint", lines: ["Import rebuilt for files over 1 GB", "Guided setup for the top three use cases", "Target: first value in under three days"], icon: "circle-check" } }],
      ["timeline", { eyebrow: "Next month", title: "Priorities everyone should know", done: 1, steps: [["Week 1", "Onboarding sprint starts", "Growth and platform pair for two weeks. Everything else waits."], ["Week 2", "Pricing page relaunch", "The new tiers go live; sales gets the talk track on Monday."], ["Week 3", "Brightline case study", "Marketing publishes; every rep gets the one-pager."], ["Week 4", "Planning week", "Q1 objectives drafted in the open. Comment on anything."]] }],
      ["team", { eyebrow: "Shoutouts", title: "People who made the difference", people: [["Aisha Bello", "Support", "Ran the night shift through the Brightline weekend without a single escalation."], ["Tomas Reyes", "Platform", "Found the import bug at 2 a.m. and shipped the fix before standup."], ["Mei Lin", "Growth", "Built the upgrade flow that crossed $100K on its own."], ["Jonah Park", "Sales", "Closed Brightline after eleven months and a lot of patience."]] }],
      ["closing", { title: "Thank you", subtitle: "Questions in the channel all week. The recording and the numbers are in the all-hands folder.", rows: [["message", "#all-hands on Slack"], ["mail", "elena@loop.example"], ["calendar", "Next all-hands: 28 November"]], cta: "Ask a question" }],
    ],
  },
  {
    id: "deck-customer-success", title: "Customer Success Review", look: "terra", rank: 70,
    tags: ["customer success", "review", "retention", "accounts"],
    meta: { company: "Fernwood", deck: "Customer success review, Q3", kicker: "The book of business", farewell: "Thanks, team",
      art: { cover: "la-conversation-illustration", section: "il-day64-followers", picture: "la-woman-working-1", closing: "od-strolling" } },
    slides: [
      ["cover", { title: "Accounts, health,\nand momentum", subtitle: "Where the book stands, the saves and the wins, what is at risk, and the expansion plays that are landing.", presenter: "Dana Whitfield, Head of Customer Success  ·  6 October 2026" }],
      ["figures", { eyebrow: "Health overview", title: "The book at a glance", stats: [["312", "Accounts", "+18 this quarter", "Twenty-six new, eight churned, all eight under fifty seats."], ["81%", "Green accounts", "+6 pts", "Health score above 70; usage and support both trending up."], ["14%", "Yellow accounts", "−4 pts", "Mostly renewals inside ninety days with a champion change."], ["5%", "Red accounts", "−2 pts", "Sixteen accounts, $1.1M in annual revenue, each with a named plan."]] }],
      ["chart", { eyebrow: "Health overview", title: "Movement between tiers", takeaway: "Twenty-two accounts moved up a tier this quarter; nine moved down. The saves programme is working.", categories: ["Red", "Yellow", "Green"], series: [{ name: "Start of quarter", values: [22, 56, 216] }, { name: "End of quarter", values: [16, 44, 252] }], calls: [["22", "Accounts moved up a tier"], ["9", "Accounts moved down"], ["$2.4M", "Renewals closed, 97% of the quarter's book"]] }],
      ["threeCards", { eyebrow: "Saves and wins", title: "Accounts we turned around", cards: [["heart", "Brightline Logistics", "Red in July after a champion left. New champion onboarded in two weeks; renewed for three years in September."], ["shield", "Meridian Health", "Blocked on a security review for four months. A named engineer cleared it in nine days."], ["sparkles", "Cobalt Retail", "Usage had halved. A workflow rebuild with their team doubled it back and added two departments."]] }],
      ["table", { eyebrow: "At risk", title: "Where we need help, and by when", cols: ["", "Revenue", "Renewal", "Ask"], rows: [["Harbor & Vale", "$240K", "November", "Exec sponsor call"], ["Summit Freight", "$180K", "December", "Integration fix"], ["Atlas Insurance", "$160K", "January", "Pricing exception"], ["Pinecrest Schools", "$120K", "November", "Training day"], ["Northwind Systems", "$95K", "December", "Roadmap commitment"]] }],
      ["process", { eyebrow: "Expansion plays", title: "The four motions that are landing", steps: [["Department to department", "A live customer walks a neighbouring team through their setup. Closed nine expansions this way."], ["Usage threshold", "At 80% of seats, the account manager books the review before the customer asks."], ["Executive business review", "Twice a year for every account over $100K. Every expansion this quarter followed one."], ["Partner referral", "Partners introduce their other customers. Four expansions, all in the first meeting."]] }],
      ["closing", { title: "Next quarter", subtitle: "Coverage moves to pods of three, the sixteen red accounts each get a named owner, and the focus list is on the wall.", rows: [["mail", "dana@fernwood.example"], ["world", "success.fernwood.example"], ["calendar", "Next review: 12 January"]], cta: "See the focus accounts" }],
    ],
  },
  {
    id: "deck-competitive-analysis", title: "Competitive Analysis", look: "slate", rank: 56,
    tags: ["competitive", "analysis", "strategy", "market"],
    meta: { company: "Form & Function", deck: "Competitive landscape, 2026", kicker: "the landscape, unsentimentally", farewell: "Decide, then move",
      art: { cover: "la-desk-illustration-2", section: "il-day65-city-road", picture: "la-working-1", closing: "la-flat-character-illustrations" } },
    slides: [
      ["cover", { title: "Who plays, and\nwhere the lines are", subtitle: "The primary rival head to head, their momentum, our edge when buyers compare, the threat that would hurt most, and our response.", presenter: "Marcus Obi, Strategy  ·  20 October 2026" }],
      ["table", { eyebrow: "Head to head", title: "Us against the primary rival", cols: ["", "Us", "Rival", "Buyer weight"], rows: [["Time to first value", "3 days", "3 weeks", "High"], ["Enterprise security", "yes", "yes", "High"], ["Open file format", "yes", "no", "Medium"], ["Self-hosting", "yes", "no", "Medium"], ["Marketplace breadth", "no", "yes", "Medium"]] }],
      ["timeline", { eyebrow: "Their momentum", title: "What they shipped this year", done: 3, steps: [["Q1", "The marketplace", "Two hundred integrations in a quarter, most of them thin. Buyers count them anyway."], ["Q2", "Usage-based pricing", "Cheaper to start, expensive at scale. Wins the pilot, loses the renewal."], ["Q3", "The AI assistant", "Fast, shallow, and demoed everywhere. Sets the expectation we now have to meet."], ["Q4", "Expected: enterprise bundle", "Their partner channel says SSO and audit logs ship by December."]] }],
      ["threeCards", { eyebrow: "Our edge", title: "Where we win when buyers compare", cards: [["bolt", "Three days to value, not three weeks", "Every won deal this year cited it. Lead with the pilot, measure it, put the number on the proposal."], ["lock", "The customer owns the data", "Open format and self-hosting close regulated buyers before price is discussed."], ["user", "One named engineer per account", "Their support is a queue. Ours has a face. Renewals mention it unprompted."]] }],
      ["statement", { text: "The move that hurts us most is not their next feature. It is a price cut we answer too late.", source: "Strategy review, October 2026" }],
      ["process", { eyebrow: "Response plan", title: "Three moves, sequenced", steps: [["Now", "Publish the pilot outcomes page. Every proposal links to it by November."], ["Q4", "Ship a real assistant, not a demo. Grounded in the customer's own files, measured on adoption."], ["Q1", "Announce the enterprise bundle before theirs lands. Same features, our security story."], ["Ongoing", "Watch pricing weekly. A cut below $30 per seat triggers the prepared response within a week."]] }],
      ["closing", { title: "Decide, then move", subtitle: "The full comparison, win-loss notes and the pricing response are in the strategy folder.", rows: [["mail", "marcus@formfunction.example"], ["world", "formfunction.example/strategy"], ["calendar", "Next review: January"]], cta: "Open the win-loss notes" }],
    ],
  },
];
