// Code generated by scripts/gen-theme.mjs from frontend/src/theme.config.mjs; DO NOT EDIT.

// Package brand holds the product/app brand identity (name + accent colors),
// single-sourced with the frontend via theme.config.mjs. It is for
// server-rendered surfaces that cannot read CSS, such as transactional email.
// Primary is brand-600 (the main interactive color); the gradient stops drive
// the brand sweep. To rebrand, edit theme.config.mjs and run `npm run gen:theme`.
package brand

const (
	Name          = "danvas"
	Primary       = "#2F55D4"
	PrimaryDark   = "#2444AE"
	GradientStart = "#2444AE"
	GradientMid   = "#2F55D4"
	GradientEnd   = "#3FA9E0"
)
