// AUTO-GENERATED by scripts/gen-theme.mjs from src/theme.config.mjs. Do not edit by hand.
// Edit colors in src/theme.config.mjs, then run `npm run gen:theme`.

export const brand = {
  "50": "#EEF2FD",
  "100": "#DCE4FB",
  "200": "#B9C9F6",
  "300": "#8DA6EE",
  "400": "#5F81E4",
  "500": "#4068DB",
  "600": "#2F55D4",
  "700": "#2444AE",
  "800": "#1D378B",
  "900": "#172C6E",
  "950": "#0E1B45",
} as const;

export const accent = {
  "50": "#EEF2FD",
  "100": "#DCE4FB",
  "200": "#B9C9F6",
  "300": "#8DA6EE",
  "400": "#5F81E4",
  "500": "#4068DB",
  "600": "#2F55D4",
  "700": "#2444AE",
  "800": "#1D378B",
  "900": "#172C6E",
  "950": "#0E1B45",
} as const;

/** Editor canvas overlay colors (React-rendered SVG/CSS overlays; the engine
 *  cannot read CSS, so these are imported as data). `selection` is a
 *  deliberate cool hue kept distinct from the brand so selections stay
 *  legible against brand-colored content. */
export const overlay = {
  selection: "#2563eb",
  guideSubtle: "#3b82f6",
  guideActive: "#06b6d4",
  guideConflict: "#f43f5e",
  penPreview: "#2444AE",
  ruler: "#9ca3af",
} as const;

/** Collaborator presence palette (assigned by a stable hash; shared with the
 *  Go backend via presence_palette_gen.go). */
export const presencePalette = [
  "#ef4444",
  "#f97316",
  "#eab308",
  "#22c55e",
  "#06b6d4",
  "#3b82f6",
  "#8b5cf6",
  "#ec4899",
  "#14b8a6",
  "#a855f7",
] as const;
export const presenceFallback = "#ef4444";

/** Avatar swatches (a distinct rainbow for telling collaborators apart). */
export const avatarColors = [
  "#e11d48",
  "#ea580c",
  "#d97706",
  "#16a34a",
  "#0891b2",
  "#2563eb",
  "#7c3aed",
  "#db2777",
] as const;
